# 开发环境配置
server:
  # 服务端口
  port: 81
  servlet:
    # 项目contextPath
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

 
# 日志配置
logging:
  level:
    io.goose: debug
    org.springframework: WARN
    org.spring.springboot.dao: debug

# Spring配置
spring:
  application:
    name: api-service
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles: 
    active: test
    
  # 文件上传
  servlet:
     multipart:
       max-file-size:  500MB
       max-request-size:  500MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  

# 防止XSS攻击
xss: 
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*


# registry center
eureka:
  client:
  # in prod or cloud env, please set enabled to true
    enabled: true
    serviceUrl:
      defaultZone: http://127.0.0.1:1111/eureka/
